---
- name: Instalacao dos pacotes - Desafio02
  apt:
   name:
     - vim
     - curl
     - telnet
     - unzip
     - wget
     - net-tools
     - htop
     - nmap
     - tree
   state: present

- name: Adicionando nome do Host
  hostname: 
    name: desafio02

- name: Adicionando usuario
  user: 
    name: laerte
    uid: 1040
    group: adm
